### ISSUE TITLE
NoMethodError on attempt to edit variants or evidence items

### ISSUE THREAD

**Issue by malachig** [genome/civic-client#169]
Observed in local instance with latest commits.  If I try to edit variants or evidence items, nothing happens and I see the following error in the log:

```
Started GET "/api/evidence_items/288/revisions" for 127.0.0.1 at 2015-07-24 14:20:42 -0500
Processing by EvidenceItemAuditsController#index as JSON
  Parameters: {"evidence_item_id"=>"288"}
  EvidenceItem Load (1.0ms)  SELECT  "evidence_items".* FROM "evidence_items" WHERE "evidence_items"."deleted" = $1 AND "evidence_items"."id" = $2 LIMIT 1  [["deleted", "f"], ["id", 288]]
  Audited::Adapters::ActiveRecord::Audit Load (0.9ms)  SELECT  "audits".* FROM "audits" WHERE "audits"."auditable_id" = $1 AND "audits"."auditable_type" = $2  ORDER BY "audits"."version" ASC LIMIT 25 OFFSET 0  [["auditable_id", 288], ["auditable_type", "EvidenceItem"]]
Completed 500 Internal Server Error in 12ms (ActiveRecord: 1.9ms)

NoMethodError - undefined method `association_viewable?' for #<Class:0x007ff5ab1a4a20>:
  activerecord (4.2.3) lib/active_record/dynamic_matchers.rb:26:in `method_missing'
  app/presenters/diff_presenter.rb:18:in `block in as_json'
  app/presenters/diff_presenter.rb:9:in `as_json'
  activesupport (4.2.3) lib/active_support/json/encoding.rb:95:in `jsonify'
  activesupport (4.2.3) lib/active_support/json/encoding.rb:91:in `block in jsonify'
  activesupport (4.2.3) lib/active_support/json/encoding.rb:91:in `jsonify'
  activesupport (4.2.3) lib/active_support/json/encoding.rb:93:in `block in jsonify'
```

**Comment by malachig** [comment]
I believe this problem has no migrated to the public instance.  I can not edit variants or evidence items.  Only genes.

**Comment by malachig** [comment]
Similarly `Evidence Talk` and `Variant Talk` do not work for me.

**Comment by acoffman** [comment]
Is it working for you now? I just pushed out a quick temporary fix to production. I'll get a real fix packaged up today.

**Comment by malachig** [comment]
Hey sorry this didn't get submitted yesterday.  Yeah this seems to have fixed the problem.  Thanks!

**Comment by acoffman** [comment]
Awesome!
